name: animated_gradient_text
description: "Create stunning animated gradient text with optional borders in Flutter. Smooth transitions, customizable colors, and spacing. Perfect for modern UI designs!"
version: 0.0.2
homepage: https://github.com/Penguin5681/Animated-Gradient-Text

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
